language: ruby
rvm:
  - 2.4.0

<<<<<<< HEAD
install: bundle install
=======
install: gem install github-pages html-proofer
>>>>>>> b00b1d2c196ca05fd52b9d7c0886aec80d00da03
script: jekyll build && htmlproofer ./_site

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build