language: ruby
rvm:
  - 2.4.0

install: gem install github-pages html-proofer
script: jekyll build && htmlproofer ./_site

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build